- name: CIS Docker Benchmark 
  hosts: docker
  become: true
  vars:
  tasks:
    - name: 1.1.1 Ensure a separate partition for containers has been created
      ansible.builtin.command:
        cmd: "{% raw %} docker info -f '{{ .DockerRootDir }}' {% endraw %}"
      register: docker_info

    - name: Check user namespace
      ansible.builtin.shell:
        cmd: "docker info | grep -q userns"
      register: userns_output
    
    - name: Set path to check
      ansible.builtin.set_fact:
        docker_root_path: "{{ docker_info.stdout }}/.."
      when: userns_output.rc == 0

    - name: Set path to check
      ansible.builtin.set_fact:
        docker_root_path: "{{ docker_info.stdout }}"
      when: userns_output.rc == 1

    - name: Check mount point 
      ansible.builtin.command:
        cmd: 'mountpoint -q -- "{{ docker_root_path }}"'
      register: mount_point
      
    - name: Pass / Fail
      ansible.builtin.assert:
        that:
          - mount_point.rc == 0
        success_msg: "[PASS] 1.1 - Separate mount point created"
        fail_msg: "[FAIL] 1.1 - No separate mount point created"
    
    - name: 1.1.2 Ensure only trusted users are allowed to control Docker daemon
      ansible.builtin.command:
        cmd: getent group docker
      register: docker_group
    
    - name: Print users in docker group
      ansible.builtin.debug:
        msg: |
          [INFO] 1.1.2 - 
          Users in docker group:\n {{ docker_group.stdout }}

    - name: 1.1.3 Ensure auditing is configured for the Docker daemon
      ansible.builtin.shell:
        cmd: apt list --installed  | grep -w auditd
      register: auditd_output

    - name: Set fact auditd is installed
      ansible.builtin.set_fact:
        auditd_present: true
      when: auditd_output.rc == 0

    - name: Set fact auditd is not installed
      ansible.builtin.set_fact:
        auditd_present: false
      when: auditd_output.rc == 1

    - name: Print result not installed
      ansible.builtin.assert:
        that:
          - auditd_present
        fail_msg: "[FAIL] 1.1.3 - auditd not installed"
      failed_when: false

    - name: Check auditing is configured
      ansible.builtin.shell:
        cmd: auditctl -l | grep /usr/bin/dockerd
      register: auditing_1_1_3
      when: auditd_present

    - name: Assert auditing is configured
      ansible.builtin.assert:
        that:
          - auditing_1_1_3.rc == 0
        success_msg: "[PASS] 1.1.3 - Auditing is configured for the Docker daemon"
        fail_msg: "[FAIL] 1.1.3 - Auditing is not configured for the Docker daemon"
      when: auditd_present
      failed_when: false

    - name: 1.1.4 Ensure auditing is configured for Docker files and directories /run/containerd
      ansible.builtin.shell:
        cmd: auditctl -l | grep /run/containerd
      register: auditing_1_1_4
      when: auditd_present

    - name: Assert auditing is configured
      ansible.builtin.assert:
        that:
          - auditing_1_1_4.rc == 0
        success_msg: "[PASS] 1.1.4 - Auditing is configured for the Docker daemon"
        fail_msg: "[FAIL] 1.1.4 - Auditing is not configured for the Docker daemon"
      when: auditd_present
      failed_when: false

    - name: Print result not installed
      ansible.builtin.assert:
        that:
          - auditd_present
        fail_msg: "[FAIL] 1.1.4 - auditd not installed"
      failed_when: false

    - name: 1.1.5 Ensure auditing is configured for Docker files and directories /var/lib/docker
      ansible.builtin.shell:
        cmd: auditctl -l | grep /var/lib/docker
      register: auditing_1_1_5
      when: auditd_present

    - name: Assert auditing is configured
      ansible.builtin.assert:
        that:
          - auditing_1_1_5.rc == 0
        success_msg: "[PASS] 1.1.5 - Auditing is configured for the Docker daemon"
        fail_msg: "[FAIL] 1.1.5 - Auditing is not configured for the Docker daemon"
      when: auditd_present
      failed_when: false

    - name: Print result not installed
      ansible.builtin.assert:
        that:
          - auditd_present
        fail_msg: "[FAIL] 1.1.5 - auditd not installed"
      failed_when: false

    - name: 1.1.6 Ensure auditing is configured for Docker files and directories /etc/docker
      ansible.builtin.shell:
        cmd: auditctl -l | grep /etc/docker
      register: auditing_1_1_6
      when: auditd_present

    - name: Assert auditing is configured
      ansible.builtin.assert:
        that:
          - auditing_1_1_6.rc == 0
        success_msg: "[PASS] 1.1.6 - Auditing is configured for the Docker daemon"
        fail_msg: "[FAIL] 1.1.6 - Auditing is not configured for the Docker daemon"
      when: auditd_present
      failed_when: false

    - name: Print result not installed
      ansible.builtin.assert:
        that:
          - auditd_present
        fail_msg: "[FAIL] 1.1.6 - auditd not installed"
      failed_when: false

    - name: 1.1.7 Ensure auditing is configured for Docker files and directories docker.service
      ansible.builtin.systemd_service:
        name: docker.service
      register: docker_service_command
      when: auditd_present
    - name: Set fact
      ansible.builtin.set_fact:
        docker_service_path: "{{ docker_service_command.status.FragmentPath }}"
    - name: Check audit rule docker.service
      ansible.builtin.shell:
        cmd: auditctl -l | grep {{ docker_service_path }}
      when: auditd_present and docker_service_path != ""
      register: docker_service_auditd
    - name: Asser file not exists
      ansible.builtin.assert:
        that:
          - docker_service_path == ""
        success_msg: "[INFO] 1.1.7 - Docker.servicefile does not exist"
      failed_when: false

    - name: Auditd not installed
      ansible.builtin.debug:
        msg: "[FAIL] 1.1.7 - auditd not installed"
      when: (not auditd_present) and docker_service_path != ""

    - name: Assert audit rule for docker.service
      ansible.builtin.assert:
        that:
          - docker_service_auditd.rc == 0
        success_msg: "[PASS] 1.1.7 - Auditing is configured for docker.service"
        fail_msg: "[FAIL] 1.1.7 - Auditing is not configured for docker.service"
      failed_when: false
      when: auditd_present and docker_service_path != ""

    - name: 1.1.8 Ensure auditing is configured for Docker files and directories containerd.sock
      ansible.builtin.stat:
        path: /run/containerd/containerd.sock
      register: containered_stats

    - name: Info if file doesnt exists
      ansible.builtin.debug:
        msg: "[INFO] 1.1.8 - Containerd.sock does not exists"
      when: not containered_stats.stat.exists

    - name: Auditd not installed
      ansible.builtin.debug:
        msg: "[FAIL] 1.1.8 - auditd not installed"
      when: (not auditd_present) and (containered_stats.stat.exists)

    - name: Check if auditing is enabled for containerd.sock
      ansible.builtin.shell:
        cmd: auditctl -l | grep /run/containerd/containerd.sock
      register: containerd_command
      when: auditd_present and containered_stats.stat.exists

    - name: Assert if auditing is enabled for containerd.sock
      ansible.builtin.assert:
        that:
          - containerd_command.rc == 0
        success_msg: "[PASS] 1.1.8 - Auditing is configured for containerd.sock"
        fail_msg: "[FAIL] 1.1.8 - Auditing is not configured for containerd.sock"
      when: auditd_present and containered_stats.stat.exists
      failed_when: false

    - name: 1.1.9 Ensure auditing is configured for Docker files and directories - docker.socket
      ansible.builtin.assert:
        that:
        - docker_service_path != ""
        fail_msg: "[INFO] 1.1. - Docker.servicefile does not exist"
      failed_when: false

    - name: Look for path
      ansible.builtin.set_fact:
        path: "{{lookup(  )}}"
        # /^ListenStream(.+)/gm