- name: CIS Docker Benchmark 
  hosts: docker
  become: true
  vars:
  tasks:
    - name: 1.1.1 Ensure a separate partition for containers has been created
      ansible.builtin.command:
        cmd: "{% raw %} docker info -f '{{ .DockerRootDir }}' {% endraw %}"
      register: docker_info

    - name: Check user namespace
      ansible.builtin.shell:
        cmd: "docker info | grep -q userns"
      register: userns_output
    
    - name: Set path to check
      ansible.builtin.set_fact:
        docker_root_path: "{{ docker_info.stdout }}/.."
      when: userns_output.rc == 0

    - name: Set path to check
      ansible.builtin.set_fact:
        docker_root_path: "{{ docker_info.stdout }}"
      when: userns_output.rc == 1

    - name: Check mount point 
      ansible.builtin.command:
        cmd: 'mountpoint -q -- "{{ docker_root_path }}"'
      register: mount_point
      
    - name: Pass / Fail
      ansible.builtin.assert:
        that:
          - mount_point.rc == 0
        success_msg: "PASS 1.1"
        fail_msg: "FAIL 1.1"
      
