global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: cis-docker-audit

scrape_configs:
  - job_name: pushgateway
    honor_labels: true
    static_configs:
      - targets:
          - pushgateway:9091

  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090
