# docker-cis-hardening.yml
---
- name: Docker CIS Hardening
  hosts: docker
  become: true
  tasks:
    - name: Install auditd
      ansible.builtin.apt:
        name:
          - auditd
          - audispd-plugins
        state: present

    - name: Configure Docker daemon
      ansible.builtin.copy:
        content: |
          {
            "icc": false,
            "log-driver": "json-file",
            "log-opts": {
              "max-size": "10m",
              "max-file": "3"
            },
            "live-restore": true,
            "userland-proxy": false,
            "no-new-privileges": true
          }
        dest: /etc/docker/daemon.json
        mode: '0644'
      notify: Restart Docker

    - name: Set Docker socket permissions
      ansible.builtin.file:
        path: /var/run/docker.sock
        owner: root
        group: docker
        mode: '0660'

#   SECTION 1 - Audit Rules
    - name: Enable audit rules for Docker (CIS 1.1.3 - 1.1.18)
      ansible.builtin.copy:
        content: |
          -w /usr/bin/dockerd -p rwxa -k docker
          -w /run/containerd -p rwxa -k docker
          -w /var/lib/docker -p rwxa -k docker
          -w /etc/docker -p rwxa -k docker
          -w /usr/lib/systemd/system/docker.service -p rwxa -k docker
          -w /run/containerd/containerd.sock -p rwxa -k docker
          -w /lib/systemd/system/docker.socket -p rwxa -k docker
          -w /etc/default/docker -p rwxa -k docker
          -w /etc/docker/daemon.json -p rwxa -k docker
          -w /etc/containerd/config.toml -p rwxa -k docker
          -w /usr/bin/containerd -p rwxa -k docker
          -w /usr/bin/containerd-shim-runc-v2 -p rwxa -k docker
          -w /usr/bin/runc -p rwxa -k docker
        dest: /etc/audit/rules.d/docker.rules
        mode: '0640'
      notify: Reload audit rules

    - name: Install lynis
      ansible.builtin.apt:
        name:
          - lynis
        state: present

    - name: Run host OS audit
      ansible.builtin.command:
        cmd: lynis audit system
      register: audit_std_out

    - name: Save host OS audit
      ansible.builtin.copy:
        content: "{{ audit_std_out.stdout }}"
        dest: lynis_audit.txt
        mode: '0644'
      delegate_to: localhost
      become: false

    - name: Update Docker
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: latest
        only_upgrade: true

#   SECTION 6 - Image Sprawl
    - name: Prune unused Docker images
      ansible.builtin.command:
        cmd: docker system prune -a -f

    - name: Prune stopped containers
      ansible.builtin.command:
        cmd: docker container prune -f

  handlers:
    - name: Restart Docker
      ansible.builtin.service:
        name: docker
        state: restarted

    - name: Reload audit rules
      ansible.builtin.command:
        cmd: augenrules --load