# docker-cis-hardening.yml
---
- name: Docker CIS Hardening
  hosts: docker
  become: yes

  tasks:
    - name: Install auditd
      ansible.builtin.apt:
        name:
          - auditd
        state: present
    - name: Configure Docker daemon
      ansible.builtin.copy:
        content: |
          {
            "icc": false,
            "log-driver": "json-file",
            "log-opts": {
              "max-size": "10m",
              "max-file": "3"
            },
            "live-restore": true,
            "userland-proxy": false,
            "no-new-privileges": true,
            "selinux-enabled": true
          }
        dest: /etc/docker/daemon.json
        mode: '0644'
      notify: Restart Docker

    - name: Set Docker socket permissions
      ansible.builtin.file:
        path: /var/run/docker.sock
        owner: root
        group: docker
        mode: '0660'

#   SECTION 1
    - name: Enable audit rules for Docker
      ansible.builtin.copy:
        content: |
          -w /usr/bin/dockerd -k docker
          -a exit,always -F path=/run/containerd -F perm=war -k docker
          -a exit,always -F path=/var/lib/docker -F perm=war -k docker
          -w /etc/docker -k docker
          -w /usr/lib/systemd/system/docker.service -k docker
          -w /run/containerd/containerd.sock -k docker
          -w /lib/systemd/system/docker.socket -k docker
          -w /etc/default/docker -k docker
          -w /etc/docker/daemon.json -k docker
          -w /etc/containerd/config.toml -k docker
          -w /usr/bin/containerd-shim-runc-v2 -k docker
          -w /usr/bin/runc -k docker

        dest: /etc/audit/rules.d/docker.rules
      notify: Reload audit rules

    - name: Install lynis
      ansible.builtin.apt:
        name:
          - lynis
        state: present
    
    - name: Run host OS audit
      ansible.builtin.command:
        cmd: lynis audit system
      register: audit_std_out
    
    - name: Save host OS audit
      ansible.builtin.copy:
        content: "{{ audit_std_out.stdout }}"
        dest: lynis_audit.txt
        mode: 644
      delegate_to: localhost
      become: false

    - name: Update Docker
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: latest
        only_upgrade: true
# SECTION 6

    - name: Ensure that image sprawl is avoided
      ansible.builtin.command:
        cmd: docker system prune -a

  handlers:
    - name: Restart Docker
      ansible.builtin.service:
        name: docker
        state: restarted

    - name: Reload audit rules
      ansible.builtin.service:
        name: auditd
        state: restarted
...